conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: /hub_data2/sojin/ffhq_1K/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 31
    intensity: 3.0
  
  noise: 
    name: poisson
    rate: 0.05
