conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: images/ffhq_1K

measurement:
  operator:
    name: motion_blur
    kernel_size: 31
    intensity: 0.5

  noise: 
    name: gaussian
    sigma: 0.05
