conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: /hub_data2/sojin/ffhq_1K/

measurement:
  operator:
    name: nonlinear_blur
    opt_yml_path: ./bkse/options/generate_blur/default.yml

  noise: 
    name: poisson
    rate: 0.05
