conditioning:
  method: ps
  params:
    scale: 1.0

data:
  name: ffhq
  root: images/ffhq_1K

measurement:
  operator:
    name: phase_retrieval
    oversample: 2.0

  noise: 
    name: poisson
    rate: 0.05
