conditioning:
  method: ps
  params:
    scale: 0.3

data:
  name: ffhq
  root: /hub_data2/sojin/ffhq_1K/

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: poisson
    rate: 0.05
